import React from 'react';
import { LessonPlan } from '../../services/geminiService';
import { parseMarkdownProcedures, ProcedureStep } from '../../utils/lessonMapper';

interface DocPreviewProps {
  data: LessonPlan | null;
  scale: number;
}

export const DocPreview: React.FC<DocPreviewProps> = ({ data, scale }) => {
  if (!data) return <div className="p-4 text-gray-500">No data to display</div>;

  const parsedProcedures = parseMarkdownProcedures(data.procedures);

  const buildKeywordsDisplay = () => {
    const zh = data.teachingPreparation?.keyWords_zh;
    const en = data.teachingPreparation?.keyWords_en;
    const zhList = Array.isArray(zh) ? zh : zh ? [zh] : [];
    const enList = Array.isArray(en) ? en : en ? [en] : [];
    const maxLength = Math.max(zhList.length, enList.length);
    if (!maxLength) return '';
    const pairs: string[] = [];
    for (let i = 0; i < maxLength; i++) {
      const enWord = enList[i] || '';
      const zhWord = zhList[i] || '';
      if (enWord && zhWord) {
        pairs.push(`${enWord} (${zhWord})`);
      } else if (enWord) {
        pairs.push(enWord);
      } else if (zhWord) {
        pairs.push(zhWord);
      }
    }
    return pairs.join(', ');
  };

  return (
    <div 
      className="origin-top-left transition-transform duration-200 bg-white shadow-lg mx-auto"
      style={{ 
        transform: `scale(${scale})`, 
        width: '210mm', 
        minHeight: '297mm',
        padding: '25.4mm',
        boxSizing: 'border-box'
      }}
    >
      <div className="font-serif leading-relaxed text-gray-800">
        <h1 className="text-3xl font-bold text-center mb-6 border-b-2 border-gray-800 pb-4">
          {data.title_zh} - Lesson Script
        </h1>

        {/* Info Block */}
        <div className="flex justify-between text-sm mb-8 italic text-gray-600 bg-gray-50 p-4 rounded">
           <span>🎓 Grade: {data.grade}</span>
           <span>⏱️ Duration: {data.duration} mins</span>
           <span>🎯 Focus: {buildKeywordsDisplay()}</span>
        </div>

        {/* Procedures Stream */}
        <div className="space-y-8">
          {parsedProcedures.map((proc: ProcedureStep, idx: number) => (
            <div key={idx} className="relative pl-6 border-l-4 border-indigo-200">
              <div className="absolute -left-[26px] top-0 w-8 h-8 bg-indigo-600 text-white rounded-full flex items-center justify-center font-bold text-sm shadow-sm">
                {idx + 1}
              </div>
              
              <h3 className="text-lg font-bold text-indigo-900 mb-2">
                {proc.title} <span className="text-sm font-normal text-gray-500 ml-2">({proc.duration} min)</span>
              </h3>

              <div className="space-y-3">
                <div className="bg-blue-50 p-3 rounded-r-lg rounded-bl-lg">
                   <span className="font-bold text-blue-700 block text-xs uppercase mb-1">📝 Procedures</span>
                   <p className="whitespace-pre-wrap">{proc.content}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-6 border-t text-center text-xs text-gray-400">
          Generated by Teacher Daily Tool • {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
};
